
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 02 16:17:39 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Extern = 27;
  public static final int Return = 30;
  public static final int Operador_relacional_Menor = 67;
  public static final int Llave_c = 87;
  public static final int Llave_a = 86;
  public static final int Std = 48;
  public static final int Coma = 97;
  public static final int Linea = 2;
  public static final int Break = 21;
  public static final int Parent_c = 85;
  public static final int Operador_relacional_DesplazamientoI = 72;
  public static final int Operador_relacional_Diferente = 69;
  public static final int Corchete_c = 89;
  public static final int Parent_a = 84;
  public static final int Corchete_a = 88;
  public static final int Operador_relacional_DesplazamientoD = 73;
  public static final int Long = 9;
  public static final int Punto = 95;
  public static final int Default = 25;
  public static final int Operador_atribucion_porIgual = 76;
  public static final int Char = 8;
  public static final int Operador_booleano_True = 81;
  public static final int Cont_Cadena = 36;
  public static final int Comillas_S = 4;
  public static final int For = 19;
  public static final int Void = 41;
  public static final int Operador_Logico_Or = 62;
  public static final int Operador_bit_a_bit_Or = 65;
  public static final int Else = 16;
  public static final int Try = 43;
  public static final int Resta = 57;
  public static final int Int = 7;
  public static final int Gets = 53;
  public static final int Nulo = 14;
  public static final int Operador_bit_a_bit_And = 64;
  public static final int Cin = 49;
  public static final int Suma = 56;
  public static final int Using = 46;
  public static final int ERROR = 101;
  public static final int Cadena = 12;
  public static final int Typedef = 38;
  public static final int Main = 90;
  public static final int Operador_atribucion_divisionIgual = 77;
  public static final int Do = 17;
  public static final int Static = 34;
  public static final int P_coma = 94;
  public static final int Signed = 32;
  public static final int Unsigned = 40;
  public static final int Operador_incremento = 79;
  public static final int Operador_atribucion_masIgual = 74;
  public static final int Short = 31;
  public static final int Scanf = 52;
  public static final int Case = 22;
  public static final int System = 91;
  public static final int Operador_relacional_menoroIgual = 71;
  public static final int Volatile = 42;
  public static final int Operador_atribucion_menosIgual = 75;
  public static final int Const = 23;
  public static final int Continue = 24;
  public static final int Operador_relacional_Mayor = 66;
  public static final int Byte = 6;
  public static final int Numeral = 83;
  public static final int Sistema = 92;
  public static final int Operador_relacional_mayoroIgual = 70;
  public static final int Operador_Logico_And = 61;
  public static final int Vacio = 13;
  public static final int Sizeof = 33;
  public static final int Operador_decremento = 80;
  public static final int Auto = 20;
  public static final int If = 15;
  public static final int Define = 51;
  public static final int Dos_P = 96;
  public static final int EOF = 0;
  public static final int Catch = 44;
  public static final int Operador_atribucion_porcentajeIgual = 78;
  public static final int Throw = 100;
  public static final int Cout = 50;
  public static final int Numero = 99;
  public static final int Double = 11;
  public static final int Struct = 35;
  public static final int Division = 60;
  public static final int Namespace = 47;
  public static final int error = 1;
  public static final int Operador_booleano_False = 82;
  public static final int Comillas = 3;
  public static final int Enum = 26;
  public static final int Float = 10;
  public static final int Identificador = 98;
  public static final int Include = 45;
  public static final int Modulo = 59;
  public static final int Printf = 93;
  public static final int Operador_relacional_Igual = 68;
  public static final int Fgets = 54;
  public static final int Register = 29;
  public static final int Operador_Logico_Not = 63;
  public static final int Igual = 55;
  public static final int Goto = 28;
  public static final int While = 18;
  public static final int Union = 39;
  public static final int B_Slash = 5;
  public static final int Multiplicacion = 58;
  public static final int Switch = 37;
}

