
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 31 17:40:19 COT 2020
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 36;
  public static final int Coma = 51;
  public static final int Nulo = 10;
  public static final int Llave_c = 44;
  public static final int Op_booleano = 39;
  public static final int Llave_a = 43;
  public static final int Unsigned = 26;
  public static final int If = 12;
  public static final int Default = 20;
  public static final int Numeral = 40;
  public static final int T_datoN = 7;
  public static final int Else = 13;
  public static final int Sistema = 27;
  public static final int Break = 19;
  public static final int Corchete_c = 46;
  public static final int Corchete_a = 45;
  public static final int Fgets = 24;
  public static final int Punto = 50;
  public static final int Vacio = 9;
  public static final int Gets = 23;
  public static final int Return = 25;
  public static final int While = 15;
  public static final int Division = 33;
  public static final int Int = 2;
  public static final int Parentesis_c = 42;
  public static final int Cadena = 8;
  public static final int Modulo = 34;
  public static final int Parentesis_a = 41;
  public static final int For = 16;
  public static final int P_coma = 48;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 17;
  public static final int Linea = 3;
  public static final int Op_atribucion = 37;
  public static final int Print = 21;
  public static final int ERROR = 54;
  public static final int Do = 14;
  public static final int SizeOf = 28;
  public static final int Op_logico = 35;
  public static final int Case = 18;
  public static final int Identificador = 52;
  public static final int Dos_P = 49;
  public static final int Comillas_S = 5;
  public static final int Scan = 22;
  public static final int Resta = 31;
  public static final int Multiplicacion = 32;
  public static final int Op_incremento = 38;
  public static final int Numero = 53;
  public static final int Suma = 30;
  public static final int Include = 11;
  public static final int Main = 47;
  public static final int B_Slash = 6;
  public static final int Igual = 29;
  public static final int Comillas = 4;
}

