
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 11 19:45:44 COT 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 31;
  public static final int Coma = 51;
  public static final int Llave_c = 38;
  public static final int Op_booleano = 34;
  public static final int Llave_a = 37;
  public static final int Unsigned = 20;
  public static final int If = 6;
  public static final int Namespace = 53;
  public static final int Void = 23;
  public static final int T_dato = 4;
  public static final int Define = 13;
  public static final int Default = 17;
  public static final int Numeral = 47;
  public static final int Typeof = 22;
  public static final int Else = 7;
  public static final int Cout = 57;
  public static final int Break = 14;
  public static final int Corchete_c = 40;
  public static final int Diple_c = 50;
  public static final int Corchete_a = 39;
  public static final int Diple_a = 49;
  public static final int Punto = 43;
  public static final int Parent_c = 36;
  public static final int Parent_a = 35;
  public static final int Return = 19;
  public static final int While = 9;
  public static final int Division = 29;
  public static final int Int = 24;
  public static final int Cadena = 5;
  public static final int For = 10;
  public static final int Std = 54;
  public static final int P_coma = 42;
  public static final int EOF = 0;
  public static final int Printf = 58;
  public static final int error = 1;
  public static final int Switch = 11;
  public static final int P_puntos = 48;
  public static final int Linea = 2;
  public static final int Op_atribucion = 32;
  public static final int ERROR = 46;
  public static final int Do = 8;
  public static final int Continue = 16;
  public static final int Op_logico = 30;
  public static final int Case = 15;
  public static final int Register = 18;
  public static final int Scanf = 56;
  public static final int Identificador = 44;
  public static final int Using = 52;
  public static final int Cin = 55;
  public static final int Struct = 21;
  public static final int Resta = 27;
  public static final int Multiplicacion = 28;
  public static final int Op_incremento = 33;
  public static final int Numero = 45;
  public static final int Suma = 26;
  public static final int Include = 12;
  public static final int Main = 41;
  public static final int Igual = 25;
  public static final int Comillas = 3;
}

